### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by R-kismeti** [avplayer/static_json#2]
你好，我下载了你的源代码，报错没有option文件，改为<experimental/option>后，编译时出现一大堆错误，多为 std::... 不是std的成员变量，我刚开始接触rapidjson，不懂得太多，解决不了，想请问你一下我该如何解决？

**Comment by alienzj** [comment]
```
pacman -S gcc
```

**Comment by alienzj** [comment]
https://en.cppreference.com/w/cpp/header/optional

**Comment by R-kismeti** [comment]
好的，非常感谢。
